"""Northena Trace-Lens — cross-engine correlation resolver (G5a).

Realises Interface Spec §16 invariant #9 (one record, seen at two scopes)
and Northena §12 (Ledger absorbs stamp-audit by unit_id + trace_id).

**READ-ONLY.** Zero writes to any persistent store. Enforced by
`test_trace_lens_readonly.py` — pytest guards Mongo write counts before +
after every route hit.

Correlation walk:
  1. Fetch all `LedgerRow`s with matching `trace_id` (Northena engine).
  2. Extract `stamp_audit` blobs — if shape matches SolvaTrace, resolve
     as Solva engine artifact.
  3. Parse `LedgerRow.reason` fields for `targeta_plan_built:{plan_id}`
     — resolve MiningPlan by plan_id (Targeta engine).
  4. For each resolved plan, resolve Registry records by `source_ref`s
     in `ordered_targets` (Mtafiti engine).
  5. Detect `service_1_converged:` prefix — mark Service 1 as touched.
"""
from datetime import datetime, timezone
from typing import Dict, List, Optional

from contracts.lift_manifest_response import LiftEntry, LiftManifestEnvelope, Rule2Accounting, SourceSpecFingerprint
from contracts.mtafiti_registry import MTAFITI_REGISTRY_COLLECTION, MtafitiRegistryRecord
from contracts.northena_ledger import NORTHENA_LEDGER_COLLECTION, LedgerRow
from contracts.targeta_plan import TARGETA_MINING_PLAN_COLLECTION, MiningPlan
from contracts.trace_lens import (
    RegistryFreshnessMarker,
    ResolvedSolvaTrace,
    TraceLensEnvelope,
)
from core import db


class TraceLensInputError(ValueError):
    """Malformed trace_id — surfaces as HTTP 400."""


class TraceLensNotFound(LookupError):
    """No Ledger rows for this trace_id — surfaces as HTTP 404."""


def _validate_trace_id(trace_id: str) -> None:
    """Malformed → TraceLensInputError. Empty/whitespace/too-long rejected.

    Length bound: 128 chars. trace_ids generated by the app are ~18 chars
    (`trace-` + 12 hex); the bound is generous but caps abuse.
    """
    if not isinstance(trace_id, str):
        raise TraceLensInputError("trace_id must be a string")
    stripped = trace_id.strip()
    if not stripped:
        raise TraceLensInputError("trace_id must be non-empty")
    if stripped != trace_id:
        raise TraceLensInputError("trace_id must not contain leading/trailing whitespace")
    if len(trace_id) > 128:
        raise TraceLensInputError("trace_id exceeds 128-char bound")


def _parse_plan_ids_from_reason(reason: Optional[str]) -> List[str]:
    """Extract plan_ids from a Ledger row's `reason` field.

    Formats observed at G4 shipping state:
      * 'targeta_plan_built:plan_<hex>'
      * 'service_1_converged:units=<n>:plan=plan_<hex>'
    """
    if not reason:
        return []
    out: List[str] = []
    if reason.startswith("targeta_plan_built:"):
        out.append(reason.split(":", 1)[1])
    else:
        for part in reason.split(":"):
            if part.startswith("plan="):
                out.append(part.split("=", 1)[1])
    return out


def _looks_like_solva_trace(stamp_audit: Optional[Dict]) -> bool:
    """Heuristic: SolvaTrace has `stages` list + `computed_class` +
    `conclusion` dict. Other stamp_audit shapes (from stamp_audit
    absorbed by G1 stamper) have `unit_id + decision + reason`.
    """
    if not isinstance(stamp_audit, dict):
        return False
    return ("stages" in stamp_audit
            and "computed_class" in stamp_audit
            and isinstance(stamp_audit.get("stages"), list))


async def resolve_trace(trace_id: str) -> TraceLensEnvelope:
    """The one-way read walk. Zero writes. Raises TraceLensInputError /
    TraceLensNotFound; the router maps to 400/404."""
    _validate_trace_id(trace_id)

    # Stage 1 — Northena Ledger rows
    ledger_docs = [
        r async for r in
        db[NORTHENA_LEDGER_COLLECTION]
        .find({"trace_id": trace_id}, {"_id": 0})
        .sort("at", 1)
    ]
    if not ledger_docs:
        raise TraceLensNotFound(f"no ledger rows for trace_id={trace_id!r}")

    ledger_rows = [LedgerRow(**doc) for doc in ledger_docs]

    engines: set = {"northena_ledger"}
    run_ids: set = set()
    solva_traces: List[ResolvedSolvaTrace] = []
    plan_ids: set = set()
    touched_service_1 = False

    for row in ledger_rows:
        if row.run_id:
            run_ids.add(row.run_id)
        # Stage 2 — Solva stamp_audit extraction
        if _looks_like_solva_trace(row.stamp_audit):
            engines.add("solva")
            solva_traces.append(ResolvedSolvaTrace(**row.stamp_audit))
        # Stage 3 — Targeta plan id extraction
        for pid in _parse_plan_ids_from_reason(row.reason):
            plan_ids.add(pid)
        # Stage 5 — Service 1 marker
        if (row.reason or "").startswith("service_1_converged:"):
            touched_service_1 = True

    # Stage 3 continued — resolve MiningPlans
    mining_plans: List[MiningPlan] = []
    for pid in plan_ids:
        doc = await db[TARGETA_MINING_PLAN_COLLECTION].find_one(
            {"plan_id": pid}, {"_id": 0}
        )
        if doc is not None:
            mining_plans.append(MiningPlan(**doc))
    if mining_plans:
        engines.add("targeta")

    # Stage 4 — resolve Mtafiti Registry records referenced by plans
    registry_records: List[MtafitiRegistryRecord] = []
    for plan in mining_plans:
        for target in plan.ordered_targets:
            reg_doc = await db[MTAFITI_REGISTRY_COLLECTION].find_one(
                {"source_ref": target.source_ref}, {"_id": 0}
            )
            if reg_doc is not None:
                registry_records.append(MtafitiRegistryRecord(**reg_doc))
    if registry_records:
        engines.add("mtafiti")

    if touched_service_1:
        engines.add("service_1")

    return TraceLensEnvelope(
        trace_id=trace_id,
        resolved_at=datetime.now(timezone.utc).isoformat(),
        run_ids=sorted(run_ids),
        engines_touched=sorted(engines),
        ledger_rows=ledger_rows,
        solva_traces=solva_traces,
        mining_plans=mining_plans,
        registry_records=registry_records,
        registry_freshness=RegistryFreshnessMarker(),
    )


# --------------------------------------------------------------------------
# Lift Manifest read surface (§G5a Step 3)
# --------------------------------------------------------------------------

import hashlib
import json as _json
from pathlib import Path


LIFT_MANIFEST_PATH = Path(__file__).parent.parent.parent / ".." / "docs" / "lift_manifest.json"
MANIFEST_MD_PATH = Path(__file__).parent.parent.parent / ".." / "docs" / "mandates" / "MANIFEST.md"
RULE2_ACCOUNTING_PATH = Path(__file__).parent.parent.parent / ".." / "docs" / "rule2_accounting.json"


def _sha256_of_file(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def _live_source_spec_sha256s() -> List[SourceSpecFingerprint]:
    """Live-computed SHA-256s of every .md file at docs/mandates/ except
    MANIFEST.md itself and phase_source_requirements.yaml. Returns the
    sorted list."""
    mandates_dir = MANIFEST_MD_PATH.parent
    fingerprints: List[SourceSpecFingerprint] = []
    for p in sorted(mandates_dir.glob("*.md")):
        if p.name == "MANIFEST.md":
            continue
        fingerprints.append(SourceSpecFingerprint(
            filename=p.name, sha256=_sha256_of_file(p),
        ))
    return fingerprints


def _load_rule2_accounting() -> Dict[str, Rule2Accounting]:
    if not RULE2_ACCOUNTING_PATH.exists():
        return {}
    data = _json.loads(RULE2_ACCOUNTING_PATH.read_text(encoding="utf-8"))
    return {
        phase: Rule2Accounting(**payload)
        for phase, payload in data.items()
        if not phase.startswith("_")  # skip metadata keys like `_note`
    }


def read_lift_manifest_envelope() -> LiftManifestEnvelope:
    """Read `docs/lift_manifest.json` fresh from disk on every call.

    Never serves stale. Freshness guaranteed by direct file read.
    Zero database writes.
    """
    payload = _json.loads(LIFT_MANIFEST_PATH.read_text(encoding="utf-8"))
    return LiftManifestEnvelope(
        manifest_version=payload["manifest_version"],
        manifest_semantics=payload["manifest_semantics"],
        generated_at=payload["generated_at"],
        generated_by=payload["generated_by"],
        substrate_state=payload["substrate_state"],
        substrate_settled_at=payload.get("substrate_settled_at"),
        entries=[LiftEntry(**e) for e in payload["entries"]],
        source_specs=_live_source_spec_sha256s(),
        phase_accounting=_load_rule2_accounting(),
    )
